extends Node

var game_script = ["Hi there! You're in a tall stone tower. We're going to be climbing to the top.",
	"Don't worry - I'll tell you a story along the way to try and keep it fresh.",
	"So hang in there! And remember, you always have a choice.",
	"Our story begins with a young girl in her late teens. We'll call her Claire.",
	"Claire lived a happy life.",
	"She did well in school, had kind parents, and good friends.",
	"In middle school, she won the statewide spelling bee.",
	"Once, she even saved a kitten from being run over by a car.",
	"Suffice to say that she was beloved, the shining star of her community.",
	"Claire lived a happy life.",
	"At least it seemed that way.",
	"Underneath her gleaming personality, Claire was troubled.",
	"She had dark thoughts.",
	"She imagined herself hurting people. Hurting animals.",
	"Hurting herself.",
	"Claire told herself that she was more than these thoughts, but they didn't stop.",
	"Lying awake at night, she would envision her death over and over.",
	"She didn't want to die, but the fantasies comforted her.",
	"As Claire grew, so did the intrusiveness of her thoughts.",
	"Without warning, she would burst into tears, or raucous laughter.",
	"Her parents became worried.",
	"Her friends didn't call as often.",
	"Her grades began to slip.",
	"And then, she started sleepwalking.",
	"At first, she didn't even realize she was doing it.",
	"She would wake up cold, with mud on her feet, or sitting on her front porch.",
	"However, little by little, Claire began to retain the memory of her walks.",
	"She wished that she hadn't.",
	"Each night, like clockwork, her body would jerk awake and make its way outside.",
	"Claire, terrified, could do nothing but watch as her body shambled around the neighborhood.",
	"Sometimes she would sit in her front lawn.",
	"Other times she would walk to the nearby houses, standing at their front doors for hours.",
	"Night after night, this would happen.",
	"Claire's anxiety grew, and the stress became unbearable.",
	"Her walks became longer, and ranged further afield.",
	"Then, during one of Claire's nightly kidnappings, she found herself at the base of the town's clocktower.",
	"Trapped within her mind, she watched in horror as her body began climbing.",
	"She struggled desperately to regain control of her body, but to no avail.",
	"She screamed for help from within her mind, but no sound escaped.",
	"And her body continued to climb.",
	"Step after step.",
	"Floor after floor.",
	"Until finally, she reached the top of the tower."]
